name: "Test docker-compose-core.yaml"
on:
  push:
    branches:
      - "**"
jobs:
  test_core:
    uses: ./.github/workflows/template-deploy.yaml
    secrets: inherit
    with:
      compose_args: "-f ./docker-compose/camunda-8.5/docker-compose-core.yaml"
      run_e2e_tests: false

